/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.beam.examples.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NestedObj extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4612367425056330943L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NestedObj\",\"namespace\":\"org.apache.beam.examples.avro\",\"fields\":[{\"name\":\"nested_int\",\"type\":\"int\"},{\"name\":\"nested_string\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NestedObj> ENCODER =
      new BinaryMessageEncoder<NestedObj>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NestedObj> DECODER =
      new BinaryMessageDecoder<NestedObj>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NestedObj> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NestedObj> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NestedObj> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NestedObj>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NestedObj to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NestedObj from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NestedObj instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NestedObj fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int nested_int;
   private java.lang.CharSequence nested_string;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NestedObj() {}

  /**
   * All-args constructor.
   * @param nested_int The new value for nested_int
   * @param nested_string The new value for nested_string
   */
  public NestedObj(java.lang.Integer nested_int, java.lang.CharSequence nested_string) {
    this.nested_int = nested_int;
    this.nested_string = nested_string;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nested_int;
    case 1: return nested_string;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nested_int = (java.lang.Integer)value$; break;
    case 1: nested_string = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'nested_int' field.
   * @return The value of the 'nested_int' field.
   */
  public int getNestedInt() {
    return nested_int;
  }


  /**
   * Sets the value of the 'nested_int' field.
   * @param value the value to set.
   */
  public void setNestedInt(int value) {
    this.nested_int = value;
  }

  /**
   * Gets the value of the 'nested_string' field.
   * @return The value of the 'nested_string' field.
   */
  public java.lang.CharSequence getNestedString() {
    return nested_string;
  }


  /**
   * Sets the value of the 'nested_string' field.
   * @param value the value to set.
   */
  public void setNestedString(java.lang.CharSequence value) {
    this.nested_string = value;
  }

  /**
   * Creates a new NestedObj RecordBuilder.
   * @return A new NestedObj RecordBuilder
   */
  public static org.apache.beam.examples.avro.NestedObj.Builder newBuilder() {
    return new org.apache.beam.examples.avro.NestedObj.Builder();
  }

  /**
   * Creates a new NestedObj RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NestedObj RecordBuilder
   */
  public static org.apache.beam.examples.avro.NestedObj.Builder newBuilder(org.apache.beam.examples.avro.NestedObj.Builder other) {
    if (other == null) {
      return new org.apache.beam.examples.avro.NestedObj.Builder();
    } else {
      return new org.apache.beam.examples.avro.NestedObj.Builder(other);
    }
  }

  /**
   * Creates a new NestedObj RecordBuilder by copying an existing NestedObj instance.
   * @param other The existing instance to copy.
   * @return A new NestedObj RecordBuilder
   */
  public static org.apache.beam.examples.avro.NestedObj.Builder newBuilder(org.apache.beam.examples.avro.NestedObj other) {
    if (other == null) {
      return new org.apache.beam.examples.avro.NestedObj.Builder();
    } else {
      return new org.apache.beam.examples.avro.NestedObj.Builder(other);
    }
  }

  /**
   * RecordBuilder for NestedObj instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NestedObj>
    implements org.apache.avro.data.RecordBuilder<NestedObj> {

    private int nested_int;
    private java.lang.CharSequence nested_string;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.beam.examples.avro.NestedObj.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nested_int)) {
        this.nested_int = data().deepCopy(fields()[0].schema(), other.nested_int);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nested_string)) {
        this.nested_string = data().deepCopy(fields()[1].schema(), other.nested_string);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing NestedObj instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.beam.examples.avro.NestedObj other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.nested_int)) {
        this.nested_int = data().deepCopy(fields()[0].schema(), other.nested_int);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nested_string)) {
        this.nested_string = data().deepCopy(fields()[1].schema(), other.nested_string);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'nested_int' field.
      * @return The value.
      */
    public int getNestedInt() {
      return nested_int;
    }


    /**
      * Sets the value of the 'nested_int' field.
      * @param value The value of 'nested_int'.
      * @return This builder.
      */
    public org.apache.beam.examples.avro.NestedObj.Builder setNestedInt(int value) {
      validate(fields()[0], value);
      this.nested_int = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nested_int' field has been set.
      * @return True if the 'nested_int' field has been set, false otherwise.
      */
    public boolean hasNestedInt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nested_int' field.
      * @return This builder.
      */
    public org.apache.beam.examples.avro.NestedObj.Builder clearNestedInt() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nested_string' field.
      * @return The value.
      */
    public java.lang.CharSequence getNestedString() {
      return nested_string;
    }


    /**
      * Sets the value of the 'nested_string' field.
      * @param value The value of 'nested_string'.
      * @return This builder.
      */
    public org.apache.beam.examples.avro.NestedObj.Builder setNestedString(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nested_string = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nested_string' field has been set.
      * @return True if the 'nested_string' field has been set, false otherwise.
      */
    public boolean hasNestedString() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nested_string' field.
      * @return This builder.
      */
    public org.apache.beam.examples.avro.NestedObj.Builder clearNestedString() {
      nested_string = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NestedObj build() {
      try {
        NestedObj record = new NestedObj();
        record.nested_int = fieldSetFlags()[0] ? this.nested_int : (java.lang.Integer) defaultValue(fields()[0]);
        record.nested_string = fieldSetFlags()[1] ? this.nested_string : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NestedObj>
    WRITER$ = (org.apache.avro.io.DatumWriter<NestedObj>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NestedObj>
    READER$ = (org.apache.avro.io.DatumReader<NestedObj>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.nested_int);

    if (this.nested_string == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.nested_string);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.nested_int = in.readInt();

      if (in.readIndex() != 0) {
        in.readNull();
        this.nested_string = null;
      } else {
        this.nested_string = in.readString(this.nested_string instanceof Utf8 ? (Utf8)this.nested_string : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.nested_int = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.nested_string = null;
          } else {
            this.nested_string = in.readString(this.nested_string instanceof Utf8 ? (Utf8)this.nested_string : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










